apiVersion: v2
name: cray-etcd-backup
version: 0.4.1
description: Configures etcd cluster backups
home: https://github.com/Cray-HPE/cray-etcd
maintainers:
  - name: bklei
  - name: brantk-hpe
  - name: kimjensen-hpe
annotations:
  artifacthub.io/images: |
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: boto3
      image: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3:1.0.0.24037
  artifacthub.io/license: MIT
