# Default values for cray-etcd-backup
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

util:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3
    tag: kubectl_v1_21_12_1.0.0.49259
    pullPolicy: IfNotPresent

crayEtcdBackup:
  periodicCronSchedule: "5 */1 * * *"

replicas: 2  # Two pods so we are resilient to one worker dropping
strategy:
  type: Recreate

pruneDayBegin: 2
pruneDayEnd: 8
