# Default values for cray-etcd-backup
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository:
  tag:
  pullPolicy: Always

boto3:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3
    tag: "1.0.0.16140"
    pullPolicy: Always

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.9
    pullPolicy: Always

crayEtcdBackup:
  imageRegistry: "dtr.dev.cray.com"
  kubectlImageVersion: "0.2.0"
  periodicCronSchedule: "0 * * * *"

replicas: 2 # Two pods so we are resillient to one worker dropping
strategy:
  type: Recreate
