---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-backup-restore
rules:
  - apiGroups: [""]
    resources: [services, endpoints, pods]
    verbs: [list, get]
  - apiGroups: ["apps"]
    resources: [statefulsets, statefulsets/scale]
    verbs: [list, get, patch, watch]
  - apiGroups: [""]
    resources: [secrets, pods/exec]
    verbs: [get, create]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [delete]
