#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-restore-config
  namespace: {{ .Release.Namespace }}
data:
  sync-snapshots-to-s3.sh: |-
    {{- .Files.Get "files/sync-snapshots-to-s3.sh" | nindent 4 }}

  create_aws_creds.sh: |-
    {{- .Files.Get "files/create_aws_creds.sh" | nindent 4 }}

  list_backups: |-
    {{- .Files.Get "files/list_backups" | nindent 4 }}

  create_backup: |-
    {{- .Files.Get "files/create_backup" | nindent 4 }}

  restore_from_backup: |-
    {{- .Files.Get "files/restore_from_backup" | nindent 4 }}
