---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup-pvc-snapshots-to-s3
  namespace: {{ .Release.Namespace }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "{{ .Values.crayEtcdBackup.periodicCronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: "etcd-backup-restore"
          containers:
          - name: sync
            image: {{ .Values.util.image.repository }}:{{ .Values.util.image.tag }}
            imagePullPolicy: {{ .Values.util.image.pullPolicy }}
            command:
              - /bin/sh
              - -c
              - create_aws_creds.sh && sync-snapshots-to-s3.sh {{ .Values.pruneDayBegin }} {{ .Values.pruneDayEnd }}
            volumeMounts:
              - name: etcd-backup-restore-config
                mountPath: /usr/local/sbin
              - name: snapshot-volume
                mountPath: /snapshots
          volumes:
            - name: snapshot-volume
              persistentVolumeClaim:
                claimName: bitnami-etcd-snapshotter
            - name: etcd-backup-restore-config
              configMap:
                name: etcd-backup-restore-config
                defaultMode: 0755
