---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-backup-restore
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    {{- .Values.strategy | toYaml | nindent 4}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cray-etcd-backup.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cray-etcd-backup.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: "etcd-backup-restore"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["{{ include "cray-etcd-backup.fullname" . }}"]
            topologyKey: kubernetes.io/hostname
      containers:
        - name: util
          image: {{ .Values.util.image.repository }}:{{ .Values.util.image.tag }}
          imagePullPolicy: {{ .Values.util.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - "create_aws_creds.sh && while true; do sleep 1000; done"
          volumeMounts:
            - name: etcd-backup-restore-config
              mountPath: /usr/local/sbin
            - name: snapshot-volume
              mountPath: /snapshots
      volumes:
        - name: etcd-backup-restore-config
          configMap:
            name: etcd-backup-restore-config
            defaultMode: 0755
        - name: snapshot-volume
          persistentVolumeClaim:
            claimName: bitnami-etcd-snapshotter
