---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-defragger
rules:
  - apiGroups: ["apps"]
    resources: [statefulsets]
    verbs: [list, get]
  - apiGroups: [""]
    resources: [pods, endpoints]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
