apiVersion: v2
name: cray-etcd-defrag
version: 0.4.1
description: Defrags etcd clusters
home: https://github.com/Cray-HPE/cray-etcd
maintainers:
  - name: bklei
  - name: kimjensen-hpe
annotations:
  artifacthub.io/images: |
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3:pet-utils-csm-1.6
  artifacthub.io/license: MIT
