apiVersion: v2
name: cray-etcd-defrag
version: 0.4.0
description: Defrags etcd clusters
home: https://github.com/Cray-HPE/cray-etcd
maintainers:
  - name: bklei
  - name: kimjensen-hpe
annotations:
  artifacthub.io/images: |
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3:kubectl_v1_21_12_1.0.0.49259
  artifacthub.io/license: MIT
