# Default values for cray-etcd-defrag
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.15
    pullPolicy: IfNotPresent

crayEtcdDefrag:
  namespace: "operators"
  defragCronSchedule: "0 0 * * *"

crayHbtdEtcdDefrag:
  defragCronSchedule: "0 */4 * * *"
  etcdClusterName: "cray-hbtd-etcd"
  ## This cronjob uses the same image as crayEtcdDefrag
