{{/*
MIT License

(C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
{{- if .Values.etcd.auth.client.secureTransport -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "cray-etcd-base.fullname" . }}-etcd-server-tls"
spec:
  secretName: "{{ include "cray-etcd-base.fullname" . }}-etcd-server-tls"
  duration: 720h
  renewBefore: 24h
  subject:
    organization:
    - Cray
  commonName: "{{ include "cray-etcd-base.fullname" . }}-{{ .Release.Namespace }}-server"
  isCA: false
  privateKey:
    size: 2048
    algorithm: rsa
    encoding: PKCS1
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "*.{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc"
    - "*.{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc.cluster.local"
    - "{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc"
    - "{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc.cluster.local"
    - "localhost"
  issuerRef:
    name: "{{ .Values.etcd.auth.client.issuer }}"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "cray-etcd-base.fullname" . }}-etcd-peer-tls"
spec:
  secretName: "{{ include "cray-etcd-base.fullname" . }}-etcd-peer-tls"
  duration: 720h
  renewBefore: 24h
  subject:
    organization:
    - Cray
  commonName: "{{ include "cray-etcd-base.fullname" . }}-{{ .Release.Namespace }}-peer"
  isCA: false
  privateKey:
    size: 2048
    algorithm: rsa
    encoding: PKCS1
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "*.{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc"
    - "*.{{ include "cray-etcd-base.fullname" . }}-etcd.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: "{{ .Values.etcd.auth.client.issuer }}"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "cray-etcd-base.fullname" . }}-etcd-tls"
spec:
  secretName: "{{ include "cray-etcd-base.fullname" . }}-etcd-tls"
  duration: 720h
  renewBefore: 24h
  subject:
    organization:
    - Cray
  commonName: "{{ include "cray-etcd-base.fullname" . }}-{{ .Release.Namespace }}-client"
  isCA: false
  privateKey:
    size: 2048
    algorithm: rsa
    encoding: PKCS1
  usages:
    - signing
    - key encipherment
    - client auth
  issuerRef:
    name: "{{ .Values.etcd.auth.client.issuer }}"
    kind: Issuer
{{- end }}
