#!/bin/sh
#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

if test "$#" -ne 2; then
    echo "Usage: has_recent_backup <project_name> <num_days_considered_recent>"
    exit 1
fi

cluster=$1
days_considered_recent=$2

endpoint=$(cat ${HOME}/.aws/s3_endpoint)
epoch_secs=$(echo "`date +%s` - (86400 * $days_considered_recent)" | bc)
date_str=$(date -d @$epoch_secs +'%Y-%m-%dT%H:%m:%S')

backups=$(aws s3api list-objects-v2 --output text --endpoint-url ${endpoint}  --prefix ${cluster} --bucket "etcd-backup" --query "Contents[?LastModified>='$date_str'].{Key: Key, LastModified: LastModified }" | sort -k 2 | awk '{print $1}')
if [ "$backups" != "None" ] && [ ! -z "$backups" ]; then
 echo "Pass"
else
 echo "Fail"
fi
