#!/bin/sh
#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

if test "$#" -ne 1; then
    echo "Usage: rebuild_cluster <project_name>"
    exit 1
fi

cluster=$1
ss_name="${cluster}-bitnami-etcd"
ns=$(kubectl get statefulsets.apps -A | grep ${ss_name} | awk '{print $1}')
kubectl scale statefulset -n ${ns} ${ss_name} --replicas=0
kubectl rollout status statefulset -n ${ns} ${ss_name}
pvc="data-${cluster}-bitnami-etcd"
echo "Deleting existing PVC's..."
kubectl delete pvc -n "${ns}" "${pvc}-0" "${pvc}-1" "${pvc}-2"
echo "Setting cluster state for ${cluster} to 'new'"
kubectl set env statefulset -n ${ns} ${ss_name} ETCD_INITIAL_CLUSTER_STATE=new
kubectl scale statefulset -n ${ns} ${ss_name} --replicas=3
kubectl rollout status statefulset -n ${ns} ${ss_name}
echo "Setting cluster state for ${cluster} to 'existing'"
kubectl set env statefulset -n ${ns} ${ss_name} ETCD_INITIAL_CLUSTER_STATE=existing
